version: '3'
services:
  fastapi:
    image: fastapi:V1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      MODEL_NAME: "${MODEL_NAME}"
      API_VERSION: "${API_VERSION}"
      AZURE_ENDPOINT: "${AZURE_ENDPOINT}"
      API_KEY: "${API_KEY}"
    
    command: ["python", "main.py"]